import ProjectDescription

/// Workspace Return Type for workspace Modifier
public final class WorkspaceModifier: WorkspaceConvertable {
    /// The name of the workspace. Also, the file name of the generated Xcode workspace.
    public var name: String
    /// The paths (or glob patterns) to manifest projects.
    public var projects: [ProjectDescription.Path]
    /// The custom schemes for the workspace. Default schemes for each target are generated by default.
    public var schemes: [ProjectDescription.Scheme]
    /// The custom file header template for Xcode built-in file templates.
    public var fileHeaderTemplate: ProjectDescription.FileHeaderTemplate?
    /// The additional files for the workspace. For project's additional files
    public var additionalFiles: [ProjectDescription.FileElement]
    /// The generation configuration of the workspace.
    public var generationOptions: ProjectDescription.Workspace.GenerationOptions

    public init(
        name: String = "",
        projects: [ProjectDescription.Path] = [],
        schemes: [ProjectDescription.Scheme] = [],
        fileHeaderTemplate: ProjectDescription.FileHeaderTemplate? = nil,
        additionalFiles: [ProjectDescription.FileElement] = [],
        generationOptions: ProjectDescription.Workspace.GenerationOptions = .options()
    ) {
        self.name = name
        self.projects = projects
        self.schemes = schemes
        self.fileHeaderTemplate = fileHeaderTemplate
        self.additionalFiles = additionalFiles
        self.generationOptions = generationOptions
    }
}

extension WorkspaceModifier {
    /// Build Workspace Type
    public func build() -> ProjectDescription.Workspace {
        return ProjectDescription.Workspace(
            name: name,
            projects: projects,
            schemes: schemes,
            fileHeaderTemplate: fileHeaderTemplate,
            additionalFiles: additionalFiles,
            generationOptions: generationOptions
        )
    }
}
