import ProjectDescription

/// Project Return Type for project Modifier
public final class ProjectModifier: ProjectConvertable {
    /// The name of the project. Also, the file name of the generated Xcode project.
    public var name: String
    /// The name of the organization used by Xcode as copyright.
    public var organizationName: String?
    /// The project options.
    public var options: ProjectDescription.Project.Options
    /// The Swift Packages used by the project.
    public var packages: [ProjectDescription.Package]
    /// The targets of the project.
    public var targets: [ProjectDescription.Target]
    /// The custom schemes for the project. Default schemes for each target are generated by default.
    public var schemes: [ProjectDescription.Scheme]
    /// The build settings and configuration for the project.
    public var settings: ProjectDescription.Settings?
    /// The custom file header template for Xcode built-in file templates.
    public var fileHeaderTemplate: ProjectDescription.FileHeaderTemplate?
    /// The additional files for the project. For target's additional files
    public var additionalFiles: [ProjectDescription.FileElement]
    /// The resource synthesizers for the project to generate accessors for resources.
    public var resourceSynthesizers: [ProjectDescription.ResourceSynthesizer]
    
    public init(
        name: String = "",
        organizationName: String? = nil,
        options: ProjectDescription.Project.Options = .options(),
        packages: [ProjectDescription.Package] = [],
        targets: [ProjectDescription.Target] = [],
        schemes: [ProjectDescription.Scheme] = [],
        settings: ProjectDescription.Settings? = nil,
        fileHeaderTemplate: ProjectDescription.FileHeaderTemplate? = nil,
        additionalFiles: [ProjectDescription.FileElement] = [],
        resourceSynthesizers: [ProjectDescription.ResourceSynthesizer] = []
    ) {
        self.name = name
        self.organizationName = organizationName
        self.options = options
        self.packages = packages
        self.targets = targets
        self.schemes = schemes
        self.settings = settings
        self.fileHeaderTemplate = fileHeaderTemplate
        self.additionalFiles = additionalFiles
        self.resourceSynthesizers = resourceSynthesizers
    }
}

extension ProjectModifier {
    /// Build Project Type
    public func build() -> ProjectDescription.Project {
        ProjectDescription.Project(
            name: name,
            organizationName: organizationName,
            options: options,
            packages: packages,
            settings: settings,
            targets: targets,
            schemes: schemes,
            fileHeaderTemplate: fileHeaderTemplate,
            additionalFiles: additionalFiles,
            resourceSynthesizers: resourceSynthesizers
        )
    }
}
