name: Bug Report
description: Found a bug in Builder? Create a report!
title: "Insert title here"
labels: ["type:bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and the expected behavior
      placeholder: A clear and concise description of what the bug is, and what you expect to happen instead.
    validations:
      required: true
  - type: textarea
    id: error-log
    attributes:
      label: Error log
      description: The full error message
      placeholder: The full error message
    validations:
      required: true
  - type: input
    id: macos-version
    attributes:
      label: macOS version
      description: Which macOS version are you using?
      placeholder: "13.0"
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Plugin version
      description: Which plugin version are you using?
      placeholder: "0.0.1"
    validations:
      required: true
  - type: input
    id: tuist-version
    attributes:
      label: Tuist version
      description: Which tuist version are you using?
      placeholder: "3.30.0"
    validations:
      required: true
  - type: input
    id: xcode-version
    attributes:
      label: Xcode version
      description: Which version of Xcode are you using?
      placeholder: "15.0.0"
    validations:
      required: true
