name: CI

on:
  push:
    branches:
      - main
      - case-key-paths
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
    macos:
        name: macos 14
        runs-on: macos-14
        strategy:
          matrix:
            config:
              - debug
              - release
        steps:
            - uses: swift-actions/setup-swift@v2
            - name: Get swift version
              run: swift --version
            - name: Checkout Package
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: View Swift Version
              run: swift --version
            - name: Build and Test
              run: |
                swift build
                swift test
