name: Docc

on:
  release:
    types:
      - published
  push:
    branches:
      - main

jobs:
  docc:
    name: Docc
    uses: jihoonme/github-workflows/.github/workflows/swift_docc.yml@main
    with:
      project_target: "TuistUI"
      hosting_path: "tuistui"
      token: ${{ secrets.GH_TOKEN }}
