name: Docc

on:
  release:
    types:
      - published
  push:
    branches:
      - main

concurrency:
  group: docc-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  docc:
    name: Docc
    uses: jihoonme/github-workflows/.github/workflows/swift_docc.yml@main
    with:
      project_target: "TuistUI"
      hosting_path: "tuistui"
