name: Release

on:
  release:
    types: [published]

jobs:
  macos:
    name: Release Tuist Plugin Zip
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Tuist
        run: brew install tuist
      - name: Generate Tuist Plugin
        run: tuist plugin archive

  upload:
    name: Upload release artifacts
    runs-on: ubuntu-latest
    needs: [macos]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: downloaded_artifacts
      - name: Display structure of downloaded files
        run: ls -R downloaded_artifacts
      - name: Upload artifact bundle
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          args: 'TuistUI.tuist-plugin.zip'
