name: Release

on:
  release:
    types: [published]

jobs:
  upload:
    name: Upload release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up Tuist
        run: curl -Ls https://install.tuist.io | bash
      - name: Generate Tuist plugin zip file
        run: tuist plugin archive
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: TuistUI.tuist-plugin.zip
          asset_name: TuistUI.tuist-plugin.zip
          asset_content_type: application/zip
